=begin
CZoB

CZoB API Specs

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
Rails.application.routes.draw do
  get '/albums', to: 'albums#show'
  post '/albums/upload', to: 'images#create'

  def add_swagger_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  add_swagger_route 'GET', '/v1/animals', controller_name: 'animals', action_name: 'index'
  add_swagger_route 'DELETE', '/v1/animals/{id}', controller_name: 'animals', action_name: 'destroy'
  add_swagger_route 'GET', '/v1/animals/{id}', controller_name: 'animals', action_name: 'show'
  add_swagger_route 'POST', '/v1/animals', controller_name: 'animals', action_name: 'create'
  add_swagger_route 'PUT', '/v1/animals', controller_name: 'animals', action_name: 'animals_put'
  add_swagger_route 'POST', '/v1/images', controller_name: 'images', action_name: 'create'
  add_swagger_route 'GET', '/v1/tags', controller_name: 'tags', action_name: 'index'
end
