=begin
CZoB

CZoB API Specs

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "animal".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :habitat
      t.integer :food
      t.string :name
      t.string :detail

      t.timestamps
    end

    create_table "error".pluralize.to_sym, id: false do |t|
      t.integer :code
      t.string :message

      t.timestamps
    end

    create_table "image".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :filename
      t.integer :animal

      t.timestamps
    end

    create_table "tag".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :type
      t.string :name

      t.timestamps
    end

  end
end
