=begin
CZoB

CZoB API Specs

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ImagesController < ApplicationController

  def create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
