=begin
CZoB

CZoB API Specs

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ImagesController < ApplicationController

  def create
    file = params[:new_image]
    image = MiniMagick::Image.open(file.tempfile.path)
    image.path
    image.format 'png'
    md5 = Digest::MD5.new
    md5 << image.to_blob
    md5 << Time.new.to_s
    md5digest = md5.hexdigest
    fn = Rails.root.join('public', 'uploads', md5digest)
    image.write "#{fn}.png"
    if Animal.exists?({name: params[:new_animal_name]})
      # adds image if animal exists
      animal = Animal.where({name: params[:new_animal_name]}).first
    else
      animal = Animal.new
      animal.name = params[:new_animal_name]
      animal.habitat = params[:new_animal_habitat]
      animal.food = params[:new_animal_food]
      animal.detail = params[:new_animal_description]

      t1_result = false
      if !Tag.exists?({typ: 0, name: animal.habitat})
        t1 = Tag.new
        t1.typ = 0
        t1.name = animal.habitat
        t1_result = t1.save
      else
        t1_result = true
      end

      t2_result = false
      if !Tag.exists?({typ: 1, name: animal.habitat})
        t2 = Tag.new
        t2.typ = 1
        t2.name = animal.food
        t2.save
        t2_result = t2.save
      else
        t2_result = true
      end

      if !(animal.save && t1_result && t2_result)
        render json: {error: 'bad request', code: 400, message: 'unable to create record'}, status: 400
        return
      end
    end

    image = Image.new
    image.animal = animal.id
    image.filename = "uploads/#{md5digest}.png"
    if image.save
      render json: animal.id.to_json
    else
      render json: {error: 'bad request', code: 400, message: 'unable to update record'}, status: 400
    end
  end
end
