=begin
CZoB

CZoB API Specs

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class TagsController < ApplicationController

  def index
    typ = params[:typ]
    ret = []
    Tag.where(typ: typ).find_each do |t|
      ret << {
        typ: t.typ,
        name: t.name
      }
    end
    render json: ret
  end
end
