=begin
CZoB

CZoB API Specs

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class Tag < ApplicationRecord
  validates :name, presence: true, uniqueness: { scope: :typ, message: 'unique tags of same typ' }, length: { in: 1..255 }
end
